baseURL = "http://stepwise.org/"
languageCode = "en-us"
title = "StepWise"
theme = "ink"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Step-by-Step Notes for Maths"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    # Optional 64x64 avatar image.
    avatar = "https://res.cloudinary.com/dtpkxwtpw/image/upload/v1586643076/my_img_cubtyr.png"

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    mode = "auto" # "dark" or "auto"
    # customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    # customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
    # customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/myicon.png"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
name = "About"
url = "/about"
weight = 3

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/gohugoio"